name: RunStaticCodeAnalysisWithESlint
run-name: ${{ github.ref_name }} RunStaticCodeAnalysisWithESlint

on: [push]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-task: ['eslint . --format json --output-file eslint_report.json bin lib']
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - name: yarn install
      run: yarn install
    - name: eslint
      run: npx ${{ matrix.lint-task }}
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@v2
      if: always()
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        report-json: 'eslint_report.json'
    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint_report.json
        path: ./eslint_report.json