name: MockDeployingResourcesToAWS
run-name: Mock AWS build action
on:
  workflow_dispatch:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: "Access Key ID with Permissions to deploy IAM, and OIDC"
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: "Secret Access Key with Permissions to deploy IAM, and OIDC"
        required: false
      AWS_REGION:
        description: "Region to deploy to."
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Configure aws credentials"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi
          
      - name: "Configure aws credentials"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi
          
      - name: "Run actions/setup-node@v2"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi
          
      - name: "Run yarn install"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi
          
      - name: "Synth stack"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi
          
      - name: "Deploy stack"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi
          
      - name: "Post configure aws credentials"
        run: |
          sleep 12
          if [[ $(( RANDOM % 20)) == 0 ]]; then
            echo "Failing step"
            exit 1
          else
            echo "Step successful"
            exit 0
          fi


