name: Review pipeline
run-name: ${{ github.ref_name }} review pipeline

on: [push]

jobs:
  Review-pipeline:
    name: Review pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
          node-version: 14
    - name: yarn install
      run: yarn install
    - name: Perform static code analysis with eslint
      run: npx eslint . --format json --output-file eslint_report.json bin lib
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@v2
      if: always()
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
        report-json: 'eslint_report.json'
    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint_report.json
        path: ./eslint_report.json
    - name: Run IaC unit tests
      run: npm test
      
